# Generated by Django 4.0.5 on 2022-07-14 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c826c8ce-6553-4b3a-8fd9-00e0973002cf'), primary_key=True, serialize=False),
        ),
    ]
