# Generated by Django 4.0.5 on 2022-07-18 00:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7dddaad4-b44c-464f-bbb7-4c03f3a4e382'), primary_key=True, serialize=False),
        ),
    ]
