# Generated by Django 4.0.5 on 2022-07-18 00:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0850f291-784d-468b-bb0f-646511b5d88b'), primary_key=True, serialize=False),
        ),
    ]
