# Generated by Django 4.0.5 on 2022-08-09 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_post_id_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ee281200-ff2c-4155-b590-228d54767211'), primary_key=True, serialize=False),
        ),
    ]
