# Generated by Django 4.0.5 on 2022-08-09 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b373cf3b-e2bc-42e4-8dec-f4736a8c94a3'), primary_key=True, serialize=False),
        ),
    ]
