# Generated by Django 4.0.5 on 2022-08-09 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('909611e6-3cf3-47a3-818f-0c5e149e70ee'), primary_key=True, serialize=False),
        ),
    ]
