# Generated by Django 4.0.5 on 2022-08-09 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55bdffef-697b-4172-86d3-18a1638e878f'), primary_key=True, serialize=False),
        ),
    ]
