# Generated by Django 4.0.5 on 2022-08-09 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6afabf9f-6bff-4b26-b2dd-e8f92553a55b'), primary_key=True, serialize=False),
        ),
    ]
