# Generated by Django 4.0.5 on 2022-09-04 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.UUID('4ca5e27a-dd41-4237-9097-63a9102acedf'), primary_key=True, serialize=False),
        ),
    ]
