# Generated by Django 4.0.5 on 2022-09-12 23:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.UUID('15d59ad5-8659-4753-a0b0-41d6928f873d'), primary_key=True, serialize=False),
        ),
    ]
